```
id:000018,sig:06,src:005253+005543,op:splice,rep:16 - 134
[New LWP 13654]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `../sqlite3 -bail'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fa73c0e3067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  0x00007fa73c0e3067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007fa73c0e4448 in __GI_abort () at abort.c:89
#2  0x00007fa73c1211b4 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7fa73c216210 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007fa73c12698e in malloc_printerr (action=1, str=0x7fa73c216318 "double free or corruption (!prev)", ptr=<optimized out>) at malloc.c:4996
#4  0x00007fa73c127696 in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
#5  0x00000000004196e2 in local_getline (zLine=<optimized out>, in=<optimized out>) at /root/build/../sqlite/src/shell.c:533
#6  0x0000000000416821 in one_input_line (in=<optimized out>, zPrior=<optimized out>, isContinuation=<optimized out>) at /root/build/../sqlite/src/shell.c:593
#7  process_input (p=<optimized out>, in=<optimized out>) at /root/build/../sqlite/src/shell.c:6876
#8  0x0000000000404ce0 in main (argc=<optimized out>, argv=<optimized out>) at /root/build/../sqlite/src/shell.c:7535
```

```
id:000076,sig:06,src:008289,op:havoc,rep:128 - 134
[New LWP 15860]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `../sqlite3 -bail'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f31ded6b067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  0x00007f31ded6b067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f31ded6c448 in __GI_abort () at abort.c:89
#2  0x00007f31deda91b4 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7f31dee9e210 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007f31dedae98e in malloc_printerr (action=1, str=0x7f31dee9e3d0 "free(): invalid next size (fast)", ptr=<optimized out>) at malloc.c:4996
#4  0x00007f31dedaf696 in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
#5  0x0000000000404d2e in set_table_name (p=<optimized out>, zName=<optimized out>) at /root/build/../sqlite/src/shell.c:2293
#6  main (argc=<optimized out>, argv=<optimized out>) at /root/build/../sqlite/src/shell.c:7538
```

```
id:000094,sig:06,src:008319+008310,op:splice,rep:128 - 139
[New LWP 16414]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `../sqlite3 -bail'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fdea65904d8 in _int_free (av=0x7fdea68bc620 <main_arena>, p=<optimized out>, have_lock=0) at malloc.c:3996
3996	malloc.c: No such file or directory.
#0  0x00007fdea65904d8 in _int_free (av=0x7fdea68bc620 <main_arena>, p=<optimized out>, have_lock=0) at malloc.c:3996
#1  0x00000000004196e2 in local_getline (zLine=<optimized out>, in=<optimized out>) at /root/build/../sqlite/src/shell.c:533
#2  0x0000000000416821 in one_input_line (in=<optimized out>, zPrior=<optimized out>, isContinuation=<optimized out>) at /root/build/../sqlite/src/shell.c:593
#3  process_input (p=<optimized out>, in=<optimized out>) at /root/build/../sqlite/src/shell.c:6876
#4  0x0000000000404ce0 in main (argc=<optimized out>, argv=<optimized out>) at /root/build/../sqlite/src/shell.c:7535
```

```
id:000194,sig:06,src:008289+009511,op:splice,rep:128 - 134
[New LWP 17272]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `../sqlite3 -bail'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fdfc221f067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  0x00007fdfc221f067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007fdfc2220448 in __GI_abort () at abort.c:89
#2  0x00007fdfc225d1b4 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7fdfc2352210 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007fdfc226298e in malloc_printerr (action=1, str=0x7fdfc23523d0 "free(): invalid next size (fast)", ptr=<optimized out>) at malloc.c:4996
#4  0x00007fdfc2263696 in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
#5  0x0000000000404d2e in set_table_name (p=<optimized out>, zName=<optimized out>) at /root/build/../sqlite/src/shell.c:2293
#6  main (argc=<optimized out>, argv=<optimized out>) at /root/build/../sqlite/src/shell.c:7538
```

```
id:000412,sig:11,src:006339+012211,op:splice,rep:2 - 139
[New LWP 18531]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `../sqlite3 -bail'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000474172 in sqlite3Init (db=0x281c6f0, pzErrMsg=0x7ffda4958ea8) at sqlite3.c:116042
116042	  ENC(db) = SCHEMA_ENC(db);
#0  0x0000000000474172 in sqlite3Init (db=0x281c6f0, pzErrMsg=0x7ffda4958ea8) at sqlite3.c:116042
#1  0x000000000047358c in sqlite3_table_column_metadata (db=0x281c6f0, zDbName=0x70b17c "main", zTableName=0x70c28f "selftest", zColumnName=0x0, pzDataType=0x0, pzCollSeq=0x0, pNotNull=0x0, pPrimaryKey=0x92e800 <__afl_area_initial>, pAutoinc=0x0) at sqlite3.c:143912
#2  0x0000000000409299 in do_meta_command (zLine=<optimized out>, p=0x7ffda495d000) at /root/build/../sqlite/src/shell.c:6023
#3  0x0000000000416d66 in process_input (p=0x7ffda495d000, in=0x7f075e7a44e0 <_IO_2_1_stdin_>) at /root/build/../sqlite/src/shell.c:6893
#4  0x0000000000404ce0 in main (argc=<optimized out>, argv=<optimized out>) at /root/build/../sqlite/src/shell.c:7535
```

```
id:000414,sig:06,src:011583,op:havoc,rep:8 - 134
[New LWP 18718]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `../sqlite3 -bail'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fa580bbe067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  0x00007fa580bbe067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007fa580bbf448 in __GI_abort () at abort.c:89
#2  0x00007fa580bfc1b4 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7fa580cf1210 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007fa580c0198e in malloc_printerr (action=1, str=0x7fa580cf1318 "double free or corruption (!prev)", ptr=<optimized out>) at malloc.c:4996
#4  0x00007fa580c02696 in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
#5  0x00000000004196e2 in local_getline (zLine=<optimized out>, in=<optimized out>) at /root/build/../sqlite/src/shell.c:533
#6  0x0000000000416821 in one_input_line (in=<optimized out>, zPrior=<optimized out>, isContinuation=<optimized out>) at /root/build/../sqlite/src/shell.c:593
#7  process_input (p=<optimized out>, in=<optimized out>) at /root/build/../sqlite/src/shell.c:6876
#8  0x0000000000404ce0 in main (argc=<optimized out>, argv=<optimized out>) at /root/build/../sqlite/src/shell.c:7535
```
